added java

diff --git a/bin/supply b/bin/supply
--- a/bin/supply
+++ b/bin/supply
@@ -30,7 +30,9 @@ export JAVA_HOME=$CACHE_DIR/jdk8u222-b10-jre/
 unzip -o $CACHE_DIR/depcheck.zip -d $CACHE_DIR/
 
 chmod +x $CACHE_DIR/dependency-check/bin/dependency-check.sh
-$CACHE_DIR/dependency-check/bin/dependency-check.sh -s $BUILD_DIR/**/*.jar
+$CACHE_DIR/dependency-check/bin/dependency-check.sh -l log --project "security-check" --failOnCVSS 1 --scan -s $BUILD_DIR/**/*.jar
+echo $?
+cat log
 
 
 echo "##################################################"
